[package]
name = "oneio"
version = "0.3.0"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/oneio"
documentation = "https://docs.rs/oneio"
description = """
OneIO is a Rust library that provides unified simple IO interface for
reading and writing to and from data files from different sources and compressions.
"""
keywords = ["io", "util"]

[[bin]]
name="oneio"
path="src/bin/oneio.rs"
required-features=["bin"]

[dependencies]
# remote
reqwest = {version="0.11", features = ["blocking"], optional=true}

# oneio
flate2 = {version = "1", optional=true }
bzip2 = {version = "0.4", optional = true }
lz4 = {version = "1.23", optional = true }
clap = {version="3.2", features=["derive"], optional=true}

[features]
default = ["all"]
all = ["remote", "gz", "bz", "lz", "bin"]
lib_only = ["remote", "gz", "bz", "lz"]

remote=["reqwest"]
gz = ["flate2"]
bz = ["bzip2"]
lz = ["lz4"]
bin = ["clap"]