[package]
name = "oneio"
version = "0.0.1"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/oneio"
documentation = "https://docs.rs/oneio"
description = """
OneIO is a Rust library that provides unified simple IO interface for
reading and writing to and from data files from different sources and compressions.
"""
keywords = ["io", "bgpkit"]

[dependencies]
tracing = "0.1"
anyhow = "1.0"
config = {version = "0.13.1", features = ["toml"]}
dirs = "4"

# remote
reqwest = {version="0.11", features = ["blocking"]}

# compression
flate2 = {version = "1", optional=true }
bzip2 = {version = "0.4", optional = true }
lz4 = {version = "1.23", optional = true }

[features]
default = ["all"]
all = ["gz", "bz", "lz"]
gz = ["flate2"]
bz = ["bzip2"]
lz = ["lz4"]