name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build default
        run: cargo build

      - name: Build no-default
        run: cargo build --no-default-features

      - name: Build lib with native-tls
        run: cargo build --no-default-features --features lib-core,native-tls

      - name: Build lib with rustls
        run: cargo build --no-default-features --features lib-core,rustls

      - name: Build lib with all features
        run: cargo build --all-features

      - name: Run test for lib + s3 features (s3 for doc compilation tests)
        run: cargo test --features s3

      - name: Run format check
        run: cargo fmt --check
